server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/h0rck/Java-cloud
          search-paths:
            - 'java-config-server*'
            - 'java-config-server/greeting-service*'
#        default-label: main